language: python
python:
  - "3.8"

# command to install dependencies
install:
  - virtualenv myvenv
  - source myvenv/bin/activate
  - pip install -r requirements.txt
  - deactivate
script:
  - echo "skipping tests"
deploy:
  provider: lambda
  function_name: "scrape-syllabus"
  region: "ap-northeast-1"
  handler_name: "lambda_handler"
  runtime: "python3.8"
  role: "arn:aws:iam::564383102056:role/AWSLambdaS3FullAccess"